# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Photography-HOTC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Photography-HOTC

  pod 'SwiftPhotoGallery'

  target 'Photography-HOTCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Photography-HOTCUITests' do
    # Pods for testing
  end

end
